### ISSUE TITLE
hlslParseables.cpp:148:15: warning: suggest parentheses around '&&' within '||' [-Wparentheses]

### ISSUE THREAD

**Issue by fbarchard** [google/glslang#4]
[834/2757] CXX obj/dreamos/external/glslang/glslang/hlslParseables.o
../../../../../../dreamos/external/glslang/hlsl/hlslParseables.cpp: In function 'glslang::TString& {anonymous}::AppendTypeName(glslang::TString&, const char*, const char*, int, int)':
../../../../../../dreamos/external/glslang/hlsl/hlslParseables.cpp:112:48: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
     if ((*argOrder == 'V' || *argOrder == 'M') && (dim0 < 1 || dim0 > 4) ||
                                                ^
../../../../../../dreamos/external/glslang/hlsl/hlslParseables.cpp: In function 'bool {anonymous}::IsValidGlsl(const char*, char, char, char, char, int, int, int, int)':
../../../../../../dreamos/external/glslang/hlsl/hlslParseables.cpp:148:15: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
     if (isMat && (argType == 'I' || argType == 'U' || argType == 'B') ||
               ^
At global scope:

The patch below adds parentheses and removes trailing spaces:
<pre>
diff --git a/hlsl/hlslParseables.cpp b/hlsl/hlslParseables.cpp
index 18f7ca4..1849103 100755
@@ -108,8 +108,8 @@ glslang::TString& AppendTypeName(glslang::TString& s, const char* argOrder, cons
         }
     }
 
-    // verify dimensions
-    if ((*argOrder == 'V' || *argOrder == 'M') && (dim0 < 1 || dim0 > 4) ||
+    // Verify dimensions.
+    if (((*argOrder == 'V' || *argOrder == 'M') && (dim0 < 1 || dim0 > 4)) ||
         (*argOrder == 'M' && (dim1 < 1 || dim1 > 4))) {
         s += "UNKNOWN_DIMENSION";
         return s;
@@ -141,12 +141,12 @@ inline bool IsValidGlsl(const char* cname, char retOrder, char retType, char arg
         return false;
 
     const std::string name(cname);  // for ease of comparison. slow, but temporary, until HLSL parser is online.
-                                
+
     if (isMat && dim0 != dim1)  // TODO: avoid mats until we find the right GLSL profile
         return false;
 
-    if (isMat && (argType == 'I' || argType == 'U' || argType == 'B') ||
-        retOrder == 'M' && (retType == 'I' || retType == 'U' || retType == 'B'))
+    if ((isMat && (argType == 'I' || argType == 'U' || argType == 'B')) ||
+        (retOrder == 'M' && (retType == 'I' || retType == 'U' || retType == 'B')))
         return false;
 
     if (name == "GetRenderTargetSamplePosition" ||
</pre>

**Comment by fbarchard** [comment]
patch take 2.
`
diff --git a/hlsl/hlslParseables.cpp b/hlsl/hlslParseables.cpp
index 18f7ca4..1849103 100755
--- a/hlsl/hlslParseables.cpp
+++ b/hlsl/hlslParseables.cpp
@@ -34,7 +34,7 @@
 //

 //
-// Create strings that declare built-in definitions, add built-ins programmatically
+// Create strings that declare built-in definitions, add built-ins programmatically
 // that cannot be expressed in the strings, and establish mappings between
 // built-in functions and operators.
 //
@@ -63,7 +63,7 @@ const char* BaseTypeName(const char* argOrder, const char* scalarName, const cha
     default:  return "UNKNOWN_TYPE";
     }
 }
-
+
 // Create and return a type name.  This is done in GLSL, not HLSL conventions, until such
 // time as builtins are parsed using the HLSL parser.
 //
@@ -88,7 +88,7 @@ glslang::TString& AppendTypeName(glslang::TString& s, const char* argOrder, cons
     case 'I': s += BaseTypeName(argOrder, "int",     "ivec",    "imat"); break;
     case 'U': s += BaseTypeName(argOrder, "uint",    "uvec",    "umat"); break;
     case 'B': s += BaseTypeName(argOrder, "bool",    "bvec",    "bmat"); break;
-    case 'S': s += BaseTypeName(argOrder, "sampler", "sampler", "sampler"); break; // TODO:
+    case 'S': s += BaseTypeName(argOrder, "sampler", "sampler", "sampler"); break; // TODO:
     default:  s += "UNKNOWN_TYPE"; break;
     }

@@ -108,8 +108,8 @@ glslang::TString& AppendTypeName(glslang::TString& s, const char* argOrder, cons
         }
     }

-    // verify dimensions
-    if ((*argOrder == 'V' || *argOrder == 'M') && (dim0 < 1 || dim0 > 4) ||
+    // Verify dimensions.
+    if (((*argOrder == 'V' || *argOrder == 'M') && (dim0 < 1 || dim0 > 4)) ||
         (*argOrder == 'M' && (dim1 < 1 || dim1 > 4))) {
         s += "UNKNOWN_DIMENSION";
         return s;
@@ -141,12 +141,12 @@ inline bool IsValidGlsl(const char* cname, char retOrder, char retType, char arg
         return false;

     const std::string name(cname);  // for ease of comparison. slow, but temporary, until HLSL parser is online.
-
+
     if (isMat && dim0 != dim1)  // TODO: avoid mats until we find the right GLSL profile
         return false;

-    if (isMat && (argType == 'I' || argType == 'U' || argType == 'B') ||
-        retOrder == 'M' && (retType == 'I' || retType == 'U' || retType == 'B'))
+    if ((isMat && (argType == 'I' || argType == 'U' || argType == 'B')) ||
+        (retOrder == 'M' && (retType == 'I' || retType == 'U' || retType == 'B')))
         return false;

     if (name == "GetRenderTargetSamplePosition" ||
@@ -201,7 +201,7 @@ inline void FindVectorMatrixBounds(const char* argOrder, int fixedVecSize, int&
     if (fixedVecSize > 0) // handle fixed sized vectors
         dim0Min = dim0Max = fixedVecSize;
 }
-
+
 } // end anonymous namespace

 namespace glslang {
@@ -398,7 +398,7 @@ void TBuiltInParseablesHlsl::initialize(int version, EProfile profile, int spv,
     // Set this to true to avoid generating prototypes that will be invalid for the GLSL parser.
     // TODO: turn it off (and remove the code) when the HLSL parser can be used to parse builtins.
     static const bool skipInvalidGlsl = true;
-
+
     // Create prototypes for the intrinsics.  TODO: Avoid ranged based for until all compilers can handle it.
     for (int icount = 0; hlslIntrinsics[icount].name; ++icount) {
         const auto& intrinsic = hlslIntrinsics[icount];
@@ -445,7 +445,7 @@ void TBuiltInParseablesHlsl::initialize(int version, EProfile profile, int spv,
                                     break;

                                 s.append(arg > 0 ? ", ": "");  // comma separator if needed
-
+
                                 if (*nthArgOrder == '>') {           // output params
                                     ++nthArgOrder;
                                     s.append("out ");
@@ -460,7 +460,7 @@ void TBuiltInParseablesHlsl::initialize(int version, EProfile profile, int spv,

                                 AppendTypeName(s, nthArgOrder, nthArgType, dim0, dim1); // Add first argument
                             }
-
+
                             s.append(");\n");            // close paren and trailing semicolon
                         }
                     }
@@ -469,7 +469,7 @@ void TBuiltInParseablesHlsl::initialize(int version, EProfile profile, int spv,
                 if (fixedVecSize > 0)  // skip over number for fixed size vectors
                     ++argOrder;
             }
-
+
             if (intrinsic.stage == EShLangAll) // common builtins are only added once.
                 break;
         }
@@ -610,7 +610,7 @@ void TBuiltInParseablesHlsl::identifyBuiltIns(int version, EProfile profile, int
     symbolTable.relateToOperator("reversebits",                 EOpBitFieldReverse);
     symbolTable.relateToOperator("round",                       EOpRoundEven);
     symbolTable.relateToOperator("rsqrt",                       EOpInverseSqrt);
-    // symbolTable.relateToOperator("saturate");
+    // symbolTable.relateToOperator("saturate");
     symbolTable.relateToOperator("sign",                        EOpSign);
     symbolTable.relateToOperator("sin",                         EOpSin);
     // symbolTable.relateToOperator("sincos");
@@ -646,7 +646,7 @@ void TBuiltInParseablesHlsl::identifyBuiltIns(int version, EProfile profile, int

 //
 // Add context-dependent (resource-specific) built-ins not handled by the above.  These
-// would be ones that need to be programmatically added because they cannot
+// would be ones that need to be programmatically added because they cannot
 // be added by simple text strings.  For these, also
 // 1) Map built-in functions to operators, for those that will turn into an operation node
 //    instead of remaining a function call.

`

**Comment by antiagainst** [comment]
Hi @fbarchard, thanks for the contribution! However, google/glslang is acting as a handy way for us to upstream patches made to [KhronosGroup/glslang](https://github.com/KhronosGroup/glslang) using GitHub's mechanism. Our goal is trying to be even with the upstream, instead of maintaining a complete diverged repo with its own patches. So would you mind file the issue against [KhronosGroup/glslang](https://github.com/KhronosGroup/glslang), which could potentially benefit a larger audience? Thanks a lot!

**Comment by fbarchard** [comment]
posted the issue here:
https://github.com/KhronosGroup/glslang/issues/383

**Comment by antiagainst** [comment]
Thanks, @fbarchard!

We'll disable issue tracking for this forked repo.
